config/routes.rb
Reservester::Application.routes.draw do

  devise_for :owners
  root to: 'restaurants#index'

  resources :restaurants

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants

  validates :first_name, :last_name, presence: true

  before_save :capitalize_names

  def capitalize_names
    self.first_name = first_name.capitalize
    self.last_name = last_name.capitalize
  end

  def name
    "#{first_name} #{last_name}"
  end
end

# == Schema Information
#
# Table name: owners
#
#  id                     :integer          not null, primary key
#  first_name             :string(255)      default(""), not null
#  last_name              :string(255)      default(""), not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#
# Indexes
#
#  index_owners_on_email                 (email) UNIQUE
#  index_owners_on_reset_password_token  (reset_password_token) UNIQUE
#

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :owner

  validates :name, :description, :street_1, :city, :zip, :state, :phone, :owner_id,
    presence: true
  validate :not_mcdonalds

  def street_address
    return street_1 if street_2.blank?
    [street_1, street_2].join(", ")
  end

  def not_mcdonalds
    errors.add(
      :name, "Unable to accept McDonalds restaurants due to trademark infringement"
    ) if name == "McDonalds"
  end
end

# == Schema Information
#
# Table name: restaurants
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  street_1    :string(255)
#  street_2    :string(255)
#  city        :string(255)
#  zip         :string(255)
#  state       :string(255)
#  phone       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  owner_id    :integer
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_owner!, except: [:index, :show]
  before_filter :assign_restaurant, only: [:show, :edit, :update, :destroy]
  before_filter :validate_authorization, only: [:edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_owner.restaurants.build(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
      flash[:notice] = "Restaurant created!"
    else
      flash[:error] = "Restaurant failed to save."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_path(@restaurant)
      flash[:notice] = "Restaurant updated!"
    else
      flash[:error] = "Restaurant failed to save."
      render :edit
    end
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path, message: "Restaurant deleted."
  end

  private

  def assign_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def validate_authorization
    unless @restaurant.owner == current_owner
      redirect_to :back
      flash[:error] = "You are not authorized to perform this action."
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :description,
      :street_1,
      :street_2,
      :city,
      :state,
      :zip,
      :phone
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

  def city_state_zip(restaurant)
    "#{restaurant.city}, #{restaurant.state} #{restaurant.zip}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservester</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "shared/login" %>

  <%= render partial: "shared/flash_messages" %>

  <div id="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :street_1 %>
  <%= f.input :street_2 %>
  <%= f.input :city %>
  <%= f.input :zip %>
  <%= f.input :state %>
  <%= f.input :phone %>
  <div class="submit">
    <%= f.button :submit, class: "btn-primary submit" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="span12">
    <div class="row">

      <h1><%= "Update #{@restaurant.name}" %></h1>
      <%= render partial: "form" %>

    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="span12">
    <div class="row">
      <h1>Restaurants</h1>
      <table class="table table-striped">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Address</th>
          <th>Phone</th>
        </tr>
        <% @restaurants.each do |restaurant| %>
          <tr>
            <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
            <td><%= restaurant.description %></td>
            <td>
              <%= restaurant.street_address %><br>
              <%= city_state_zip(restaurant) %>
            </td>
            <td><%= restaurant.phone %></td>
          </tr>
        <% end %>
      </table>

      <% if current_owner %>
        <%= button_to "Add a new restaurant", new_restaurant_path, method: :get, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="span12">
    <div class="row">

      <h1>Create New Restaurant</h1>
      <%= render partial: "form" %>

    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="span12">
    <div class="row">
      <%= link_to "<< Back to all restaurants", restaurants_path, class: "top-link" %>
      <h1><%= @restaurant.name %></h1>
      <table class="table" id="restaurant-show">
        <tr>
          <td><strong>Description</strong></td>
          <td><%= @restaurant.description %></td>
        </tr>
        <tr>
          <td><strong>Address</strong></td>
          <td>
            <%= @restaurant.street_address %><br>
            <%= city_state_zip(@restaurant) %>
          </td>
        </tr>
        <tr>
          <td><strong>Phone</strong></td>
          <td><%= @restaurant.phone %></td>
        </tr>
        <tr>
          <td><strong>Owner</strong></td>
          <td><%= @restaurant.owner.name %></td>
        </tr>
      </table>

      <% if current_owner && @restaurant.owner == current_owner %>
        <div class="btn-group">
          <%= button_to "Edit", edit_restaurant_path(@restaurant), method: :get, class: "btn btn-primary" %>
          <%= button_to "Delete", restaurant_path(@restaurant), method: :delete, confirm: "Are you sure you want to delete this restaurant?", class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <% alerts = { :error => "danger", :notice => "info", :info => "info", :alert => "danger" } %>
      <% alerts.keys.each do |alert| %>
        <% if flash[alert] %>
          <div class="alert alert-<%= alerts[alert] %> alert-dismissable">
            <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
            <%= flash[alert] %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_login.html.erb
<div class="container">
  <div class="span12">
    <div class="row">
      <% if current_owner %>
        <%= link_to "Log out", destroy_owner_session_path, method: :delete %>
      <% else %>
        <%= link_to "Log in", new_owner_session_path %> or <%= link_to "Sign up", new_owner_registration_path %>
      <% end %>
    </div>
  </div>
</div>